### ISSUE TITLE
What version of caffe2 do you use?

### ISSUE THREAD

**Issue by aiskhak** [cics-nd/rans-uncertainty#11] opened 2020-10-09 21:51 UTC
It looks like like old function do not work in pytorch version of caffe2. When compiling reynoldsNet I am getting following errors:

reynoldsNet.C: In member function ‘std::vector<float> caffe2::reynoldsNet::forward(std::vector<float>) const’:
reynoldsNet.C:87:52: error: no matching function for call to ‘caffe2::Tensor::Tensor(<brace-enclosed initializer list>, std::vector<float>&, caffe2::CPUContext*)’
   auto inputTensor = Tensor({1, 5}, inputdata, &ctx);

/home/aiskhak/anaconda3/pkgs/pytorch-nightly-cpu-1.2.0.dev20190731+cpu-py3.7_cpu_0/lib/python3.7/site-packages/torch/include/caffe2/core/tensor.h:29:3: note:   candidate expects 2 arguments, 3 provided
reynoldsNet.C:101:62: error: use of deleted function ‘caffe2::Tensor::Tensor(const caffe2::Tensor&)’
   auto outBlob = workSpace.GetBlob("output")->Get<TensorCPU>();

Could you please help me resolve these issues?

Regards,
Arsen

**Comment by NickGeneva** [comment] 2020-10-12 15:47
I am not sure what Caffe version I used, and current documentation seems to just be replaces with pytorch links. As stated in the repository the provided files are not intended to be a directly used but rather serve as a starting point for others. This is because of machine dependencies with installed libraries and that caffe2 merged with pytorch right after this repository was released. Making everything essentially obsolete the moment it was pushed.

If want to get pytorch and openfoam coupled my suggestions would be to directly used the PyTorch c++ apis instead. This will allow you to avoid the pytorch-onnx-caffe2 conversion headaches which was necessary at the time.

**Comment by aiskhak** [comment] 2020-10-12 15:51
Thank you for your answer. 
My research shows that it is not possible to install "old" caffe2. Only pytorch versions are available. I believe that C++ libraries in the repository will not work since they changed some functions, etc. (API)

I am a newbie in OpenFOAM.
Could you provide some references on how to use a NN in OpenFOAM, or how to migrate these C++ libraries from caffe2 to pytorch?

Thank you

**Comment by 3014214149** [comment] 2021-01-08 07:42
aiskhak,
I meet the same problem with you. Have you solved it ？

**Comment by NickGeneva** [comment] 2021-01-08 13:58
Some additional details.

Back when this code was written Caffe2 was included in the PyTorch Library for the listed version 1.0.0. With present versions of PyTorch it is my understanding that Caffe2 is now evolved into direct C++ Pytorch API instead of a separate entity. That is why I suggest to use updated APIs. Alternatively try to use the Caffe2 included in PyTorch 1.0.0 (have no idea what version this is).

In order to compile a turbulence model in OpenFOAM with any sort of machine learning/external C++ library. You will have to add links to the libraries in the "options" file found in the [options file](https://github.com/cics-nd/rans-uncertainty/blob/master/sdd-rans/TurbulenceModels/turbulenceModels/Make/options) if they are not in some default environment variable. This file provides the make file compiler options for this particular model.

You can manually link a library with -L "path to file" compiler option.

**Comment by aiskhak** [comment] 2021-01-09 00:03
> aiskhak,
> I meet the same problem with you. Have you solved it ？

Hi. I do believe that due to updates of Caffe, the C++ scripts must be substantially revisited.

Nowadays, Pytorch provides a better opportunity to save a NN for C++ program (Torch script), see here: https://pytorch.org/tutorials/advanced/cpp_export.html

Torch script will also require significant changes of the C++ scripts for the framework's realization, but avoids such steps as converting to Caffe and so on.

**Comment by 3014214149** [comment] 2021-01-09 07:31
> Some additional details.
> 
> Back when this code was written Caffe2 was included in the PyTorch Library for the listed version 1.0.0. With present versions of PyTorch it is my understanding that Caffe2 is now evolved into direct C++ Pytorch API instead of a separate entity. That is why I suggest to use updated APIs. Alternatively try to use the Caffe2 included in PyTorch 1.0.0 (have no idea what version this is).
> 
> In order to compile a turbulence model in OpenFOAM with any sort of machine learning/external C++ library. You will have to add links to the libraries in the "options" file found in the [options file](https://github.com/cics-nd/rans-uncertainty/blob/master/sdd-rans/TurbulenceModels/turbulenceModels/Make/options) if they are not in some default environment variable. This file provides the make file compiler options for this particular model.
> 
> You can manually link a library with -L "path to file" compiler option.

Geneva，

I tried to manually link a library with -L "path to file" compiler option. I modified -L <LOCATION OF CAFFE2 LIBS> to -L </home/username/anaconda3/envs/mytorch/lib/python3.6/site-packages/torch/lib>, but it still didn't work. Does it mean that I added wrong library?

**Comment by 3014214149** [comment] 2021-01-09 07:37
> It looks like like old function do not work in pytorch version of caffe2. When compiling reynoldsNet I am getting following errors:
> 
> reynoldsNet.C: In member function ‘std::vector caffe2::reynoldsNet::forward(std::vector) const’:
> reynoldsNet.C:87:52: error: no matching function for call to ‘caffe2::Tensor::Tensor(, std::vector&, caffe2::CPUContext*)’
> auto inputTensor = Tensor({1, 5}, inputdata, &ctx);
> 
> /home/aiskhak/anaconda3/pkgs/pytorch-nightly-cpu-1.2.0.dev20190731+cpu-py3.7_cpu_0/lib/python3.7/site-packages/torch/include/caffe2/core/tensor.h:29:3: note: candidate expects 2 arguments, 3 provided
> reynoldsNet.C:101:62: error: use of deleted function ‘caffe2::Tensor::Tensor(const caffe2::Tensor&)’
> auto outBlob = workSpace.GetBlob("output")->Get();
> 
> Could you please help me resolve these issues?
> 
> Regards,
> Arsen

I met the same error. It seems that the tensor.h in pytorch is inconsistent with author's. So the arguments number was wrong.

**Comment by 3014214149** [comment] 2021-01-09 13:56
> It looks like like old function do not work in pytorch version of caffe2. When compiling reynoldsNet I am getting following errors:
> 
> reynoldsNet.C: In member function ‘std::vector caffe2::reynoldsNet::forward(std::vector) const’:
> reynoldsNet.C:87:52: error: no matching function for call to ‘caffe2::Tensor::Tensor(, std::vector&, caffe2::CPUContext*)’
> auto inputTensor = Tensor({1, 5}, inputdata, &ctx);
> 
> /home/aiskhak/anaconda3/pkgs/pytorch-nightly-cpu-1.2.0.dev20190731+cpu-py3.7_cpu_0/lib/python3.7/site-packages/torch/include/caffe2/core/tensor.h:29:3: note: candidate expects 2 arguments, 3 provided
> reynoldsNet.C:101:62: error: use of deleted function ‘caffe2::Tensor::Tensor(const caffe2::Tensor&)’
> auto outBlob = workSpace.GetBlob("output")->Get();
> 
> Could you please help me resolve these issues?
> 
> Regards,
> Arsen

I tried to modify tensor.h. It seems that you should added Variable type declaration in tensor.h. But I don't know how to do it. Hope it will help you.

**Comment by NickGeneva** [comment] 2021-01-10 16:30
> 
> Geneva，
> 
> I tried to manually link a library with -L "path to file" compiler option. I modified -L to -L </home/username/anaconda3/envs/mytorch/lib/python3.6/site-packages/torch/lib>, but it still didn't work. Does it mean that I added wrong library?

I would try using a higher directory like /home/username/anaconda3/envs/mytorch/lib/python3.6/site-packages/torch/ or even /home/username/anaconda3/envs/mytorch/lib/python3.6/site-packages/ to make sure the caffe2 c++ files are somewhere in the sub directory.

Best I can help with for now. You may also want to try older versions of caffe2 in some of the older PyTorch releases. Like I explicitly mention I decided to not support this aspect of the code since the caffe2 to pytorch versions were transitioning right around publication.

**Comment by 3014214149** [comment] 2021-01-11 06:22
I have solved the compiler problem for ReynoldsNet.The problem was caused by a change in the template of the Tensor file after the merger of PyTorch and Caffe2.The easiest way to do this is to modify the call format of Tensor in the ReynoldsNet file.Modify as follows.Replace lines 86,87 of the source with the following code

code
at::ArrayRef<float> dataRef(inputdata);
vector<int> dim;
dim.push_back(1);
dim.push_back(5);
at::IntList *pdims;
pdims = new at::IntList(dim);
auto inputTensor = TensorCPUFromValues(*pdims, dataRef);

**Comment by NickGeneva** [comment] 2021-01-11 13:45
Closing issue for now, will link this in readme for others to reference.

**Closed as completed by NickGeneva** 2021-01-11 13:45 UTC
Labels: bug, question
